### ISSUE TITLE
KH也想要个

### ISSUE THREAD

**Issue by KHLFYY** [CrSjimo/junze#2]
既然有了junze x2和赵总 
为什么不顺便加个KH的呢
虽然不知道有什么文案

**Comment by CrSjimo** [comment]
计划增加自定义模式，使用者可以自行设置文字内容

________________________________
发件人: KHLFYY ***@***.***>
发送时间: 2021年7月17日星期六 22:34
收件人: CrSjimo/junze
抄送: Subscribed
主题: [CrSjimo/junze] KH也想要个 (#2)


既然有了junze x2和赵总
为什么不顺便加个KH的呢
虽然不知道有什么文案

―
