### ISSUE TITLE
自定义的建议：将语法词换为按钮

### ISSUE THREAD

**Issue by KHLFYY** [CrSjimo/junze#3]
建议把自定义的“%d”等语法词换为一个交互按钮输入 并在按钮上注明实际意义 以提升使用体验

**Comment by CrSjimo** [comment]
任何想要添加的新功能都可以通过在eval模式里写代码来自行添加，不妨试试。
发件人: ***@***.***>
发送时间: 2021年7月31日 19:55
收件人: ***@***.***>
抄送: ***@***.***>
主题: [CrSjimo/junze] 自定义的建议：将语法词换为按钮 (#3)


建议把自定义的“%d”等语法词换为一个交互按钮输入 并在按钮上注明实际意义 以提升使用体验

―

**Comment by KHLFYY** [comment]
呃呃 好像不是我表达的意思 但是有了内置帮助这个功能鸽了问题也不大
