### ISSUE TITLE
将实验模式将“了解更多”单开网页改为显示折叠文字

### ISSUE THREAD

**Issue by KHLFYY** [CrSjimo/junze#4]
不知道这个实现起来有没有难度，或者用其他的形式，总之是把“了解更多”里的各种标记（语法词）那个表，直接显示出来，要不每次输入都得反复横跳查表。

**Comment by CrSjimo** [comment]
在eval模式中输入：

```
`;let _=document.createElement('iframe');_.src='tips.html';_.id="khlfyy";document.body.appendChild(_);`
```

然后点击“单抽”，即可显示嵌入式帮助界面。

在eval模式中输入：

```
`;document.getElementById('khlfyy').remove();`
```

然后点击“单抽”，即可关闭嵌入式帮助界面。

**Comment by KHLFYY** [comment]
> 在eval模式中输入：
> 
> ```
> `;let _=document.createElement('iframe');_.src='tips.html';_.id="khlfyy";document.body.appendChild(_);`
> ```
> 
> 然后点击“单抽”，即可显示嵌入式帮助界面。
> 
> 在eval模式中输入：
> 
> ```
> `;document.getElementById('khlfyy').remove();`
> ```
> 
> 然后点击“单抽”，即可关闭嵌入式帮助界面。

[BUG]输入之后多次点击抽卡按钮 会叠加很多个帮助界面
![image_75](https://user-images.githubusercontent.com/76054116/127774042-d26fcbe1-d616-4ec2-8247-62723b90de35.png)

**Comment by KHLFYY** [comment]
这个不错 但是 能不能把``;let _=document.createElement('iframe');_.src='tips.html';_.id="khlfyy";document.body.appendChild(_);`
`再精简一下呢

**Comment by KHLFYY** [comment]
这个不错 但是能不能把`;let _=document.createElement('iframe');_.src='tips.html';_.id="khlfyy";document.body.appendChild(_);
`再精简一下呢

**Comment by CrSjimo** [comment]
别一直点，点一次就行

获取 Outlook for Android

________________________________

**Comment by KHLFYY** [comment]
能不能把帮助的那条精简一下 变成%help 啥的
